UXX = u++
UXXFLAGS = -g -std=c++1y -multi -nodebug -Wall -Wno-unused-label -O2
OBJECTS = main.cc
TARGET = soda

soda:
	${UXX} ${UXXFLAGS} ${OBJECTS} -o ${TARGET}

clean:
	${RM} ${TARGET}

.PHONY: soda
